title: Sandra Romero
logo: https://github.com/sandrarors/sandraromero.github.io/blob/main/Profile.png
#description Analista de Datos con experiencia en Marketing y Gestión de Proyectos. Especializada en la interpretación y visualización de datos para la toma de decisiones.
theme: jekyll-theme-minimal  
